# sensor_data_dir: /Users/mac/Library/CloudStorage/Dropbox/dataset/sensor_data
# sensor_data_dir: /Users/hien/Dropbox/dataset/sensor_data
sensor_data_dir: /Users/test/Dropbox/dataset/sensor_data
visual_data_dir: /Users/test/Dropbox/dataset/visual_data
pred_behav_dir: /Users/test/Dropbox/dataset/visual_data/pred_behaviors